version: 2.1
orbs:
  maven-build: inclasstoday/maven-build@2.1.1
workflows:
  version: 2.1
  verify_and_build:
    jobs:
      - maven-build/docker_build:
          context: maven-build
          pre-steps:
            - run:
                name: Setting environment vars
                command: |
                  echo "Set environment vars"
                  printenv >> ${BASH_ENV}
                environment:
                  - DB_HOST: postgres
                  - SFTP_HOST: sftp-container
          with_docker: true
          copy_docker_resources: docker
          run_docker_compose: true
